commerce_order.commerce_order_type.*:
  type: config_entity
  label: 'Order type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'

content.*.settings:
  type: mapping
  label: 'Inline Entity Form settings'
  mapping:
    match_operator:
      type: string
      label: 'Match Operator'